"""empty message

Revision ID: 2c105c017745
Revises: 8797339f4d4c
Create Date: 2021-02-11 13:54:46.910462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c105c017745'
down_revision = '8797339f4d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('label', table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('label', 'tasks', ['label'], unique=True)
    # ### end Alembic commands ###
